runtime: php73
api_version: 1

handlers:
- url: /
  script: index.php
- url: /login\.php
  script: login.php
- url: /register\.php
  script: register.php
- url: /home\.php
  script: home.php
- url: /logout\.php
  script: logout.php
- url: /send\.php
  script: send.php
- url: /show_messages\.php
  script: show_messages.php
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.(php|css|js))$
  script: \10
  
- url: /css
  static_dir: css
  
- url: /img
  static_dir: img
  
- url: /js
  static_dir: js
  
- url: /sound
  static_dir: sound
